# Generated by Django 6.0 on 2025-12-12 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_specialist', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sobre mim')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço da Consulta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
