# Generated by Django 6.0 on 2025-12-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('Tecnologia e TI', 'Tecnologia e TI'), ('Consultoria Jurídica', 'Consultoria Jurídica'), ('Consultoria Financeira', 'Consultoria Financeira'), ('Saúde e Bem-estar', 'Saúde e Bem-estar'), ('Marketing Digital', 'Marketing Digital'), ('Coaching Profissional', 'Coaching Profissional'), ('Design e Criatividade', 'Design e Criatividade'), ('Engenharia e Arquitetura', 'Engenharia e Arquitetura'), ('Outros', 'Outros')], max_length=100, null=True, verbose_name='Área de Atuação'),
        ),
    ]
