# Generated by Django 5.0.2 on 2025-12-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_active_plan',
            field=models.BooleanField(default=False, verbose_name='Tem Plano Ativo?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de Perfil'),
        ),
    ]
