# Generated by Django 5.0.2 on 2025-12-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_has_active_plan_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_type',
            field=models.CharField(choices=[('nenhum', 'Não definido'), ('assinatura', 'Assinante (Plano Mensal)'), ('avulso', 'Pagamento Avulso (Por Consulta)')], default='nenhum', max_length=20, verbose_name='Tipo de Acesso'),
        ),
    ]
